#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_GOOGLE_include_directive : require

#include "particleInfo.hpp"
#include "projview.hpp"

struct DrawIndirectCommand {
    uint vertexCount;
    uint instanceCount;
    uint firstVertex;
    uint firstInstance;
};

#define BLOCK_SIZE PARTICLE_SIMULATOR_BLOCK_SIZE
layout(local_size_x = BLOCK_SIZE) in;

layout(set = 0, binding = 0, std430) buffer et_t{
  EmitterInfo       einfo[N_MAX_EMITTERS];
  EmitterSpawnInfo espawn[N_MAX_EMITTERS];
};


layout(set = 0, binding = 1) buffer res_t  { vec4 res [N_MAX_PARTICLES_TOTAL]; };
layout(set = 0, binding = 2) buffer cmd_t  { DrawIndirectCommand cmd [N_MAX_EMITTERS]; };

layout(set = 0, binding = 3) buffer ppos_t { vec4 ppos[N_MAX_PARTICLES_PER_EMITTER]; vec4 pvel[N_MAX_PARTICLES_PER_EMITTER]; } edata[N_MAX_EMITTERS];

layout(set = 1, binding = 0) uniform WVPM_t {
  WorldViewProjMatrices world;
};


layout(push_constant) uniform pc {
    mat4 mProjView;
    float frameTime;
    float dt;
} params;

float rand(vec2 c){
	return fract(sin(dot(c.xy, vec2(12.7898,78.233)) + cos(dot(c.xy, vec2(-12315.5767, 3524.56)))) * 43718.5453);
}

shared uint randSeed;
float randf() {
    return rand(params.frameTime * vec2(gl_WorkGroupID.x, atomicAdd(randSeed, 1)));
}

float randsf() {
    return 2 * randf() - 1;
}

vec3 randvec3() {
    return 2 * vec3(randf(), randf(), randf()) - vec3(1);
}

vec3 randnvec3() {
    return normalize(2 * vec3(randf(), randf(), randf()) - vec3(1));
}

uint ceilPowerOfTwo(uint v) {
    v--;
    v |= v >> 1;
    v |= v >> 2;
    v |= v >> 4;
    v |= v >> 8;
    v |= v >> 16;
    v++;
    return v;
}


void emitParticle(uint dst) {
    uint emitter = gl_WorkGroupID.x;
    const vec3 pos = einfo[emitter].position.xyz + espawn[emitter].spawnRadius * randvec3();
    const vec3 dir = mix(randnvec3(), espawn[emitter].direction.xyz, espawn[emitter].direction.a);

    const vec3 vel = espawn[emitter].maxSpeed * mix(1, randf(), espawn[emitter].speedRandomFactor) * dir;

    edata[emitter].ppos[dst].xyz = pos;
    edata[emitter].ppos[dst].w = 0;
    barrier();

    edata[emitter].pvel[dst].xyz = vel;
    edata[emitter].pvel[dst].w   = 1 / max(0.001f, espawn[emitter].lifetime + espawn[emitter].lifetimeRandomFactor * randsf());
    barrier();
}


shared uint reducerBuf[BLOCK_SIZE];
void bufReduce() {
    barrier();
    if(gl_LocalInvocationID.x + BLOCK_SIZE / 2 < BLOCK_SIZE) {
    #if BLOCK_SIZE >= 2
        reducerBuf[gl_LocalInvocationID.x] += reducerBuf[gl_LocalInvocationID.x + BLOCK_SIZE /    2]; memoryBarrierShared();
    #endif
    #if BLOCK_SIZE >= 4
        reducerBuf[gl_LocalInvocationID.x] += reducerBuf[gl_LocalInvocationID.x + BLOCK_SIZE /    4]; memoryBarrierShared();
    #endif
    #if BLOCK_SIZE >= 8
        reducerBuf[gl_LocalInvocationID.x] += reducerBuf[gl_LocalInvocationID.x + BLOCK_SIZE /    8]; memoryBarrierShared();
    #endif
    #if BLOCK_SIZE >= 16
        reducerBuf[gl_LocalInvocationID.x] += reducerBuf[gl_LocalInvocationID.x + BLOCK_SIZE /   16]; memoryBarrierShared();
    #endif
    #if BLOCK_SIZE >= 32
        reducerBuf[gl_LocalInvocationID.x] += reducerBuf[gl_LocalInvocationID.x + BLOCK_SIZE /   32]; memoryBarrierShared();
    #endif
    #if BLOCK_SIZE >= 64
        reducerBuf[gl_LocalInvocationID.x] += reducerBuf[gl_LocalInvocationID.x + BLOCK_SIZE /   64]; memoryBarrierShared();
    #endif
    #if BLOCK_SIZE >= 128
        reducerBuf[gl_LocalInvocationID.x] += reducerBuf[gl_LocalInvocationID.x + BLOCK_SIZE /  128]; memoryBarrierShared();
    #endif
    #if BLOCK_SIZE >= 256
        reducerBuf[gl_LocalInvocationID.x] += reducerBuf[gl_LocalInvocationID.x + BLOCK_SIZE /  256]; memoryBarrierShared();
    #endif
    #if BLOCK_SIZE >= 512
        reducerBuf[gl_LocalInvocationID.x] += reducerBuf[gl_LocalInvocationID.x + BLOCK_SIZE /  512]; memoryBarrierShared();
    #endif
    #if BLOCK_SIZE >= 1024
        reducerBuf[gl_LocalInvocationID.x] += reducerBuf[gl_LocalInvocationID.x + BLOCK_SIZE / 1024]; memoryBarrierShared();
    #endif
    #if BLOCK_SIZE >= 2048
    #error "BLOCK_SIZE >= 2048 not implemented"
    #endif
    }
    barrier();
}

void simulateEmitter(uint start, uint size) {
    reducerBuf[gl_LocalInvocationID.x] = 0;
    barrier();
    for(uint i = 0; i < N_MAX_PARTICLES_PER_EMITTER; i += BLOCK_SIZE) {
        edata[gl_WorkGroupID.x].ppos[i+gl_LocalInvocationID.x] += params.dt * edata[gl_WorkGroupID.x].pvel[i+gl_LocalInvocationID.x];
        edata[gl_WorkGroupID.x].pvel[i+gl_LocalInvocationID.x] += params.dt * vec4(0, -espawn[gl_WorkGroupID.x].gravity, 0, 0);
        if (edata[gl_WorkGroupID.x].ppos[i+gl_LocalInvocationID.x].w < 1) {
            reducerBuf[gl_LocalInvocationID.x]++;
        }
    }
    bufReduce();
    if(gl_LocalInvocationID.x == 0) {
        einfo[gl_WorkGroupID.x].count = N_MAX_PARTICLES_PER_EMITTER;
        einfo[gl_WorkGroupID.x].count = reducerBuf[0];
    }
    barrier();
}

void moveToRes(uint eidx)
{
    uint start = cmd[eidx].firstInstance;
    uint size  = ceilPowerOfTwo(max(2*BLOCK_SIZE, cmd[eidx].instanceCount));
    for(uint i = gl_LocalInvocationID.x; i < size; i += BLOCK_SIZE) {
        res[start + i] = edata[gl_WorkGroupID.x].ppos[i];
    }
    barrier();
}

uint compare(vec4 lhs, vec4 rhs) {
    uint live1 = lhs.w < 1 ? 1 : 0;
    uint live2 = rhs.w < 1 ? 1 : 0;
    if(live1 != live2) 
        return live1 < live2 ? 1 : 0;
    if(einfo[gl_WorkGroupID.x].type == 6) {
        return lhs.w > rhs.w ? 1 : 0;
    }
    return (world.mProjView[0] * vec4(lhs.xyz, 1)).z < (world.mProjView[0] * vec4(rhs.xyz, 1)).z ? 1 : 0;
}

#define SORT_PPOS

shared vec4 cachePpos[2 * BLOCK_SIZE];
#ifdef SORT_PPOS
shared vec4 cachePvel[2 * BLOCK_SIZE];
#endif
void sortCached(uint start, uint reverse) {
    const uint idx = gl_LocalInvocationID.x;
    #ifdef SORT_PPOS
    cachePpos[idx]              = edata[gl_WorkGroupID.x].ppos[start + idx];
    cachePpos[idx + BLOCK_SIZE] = edata[gl_WorkGroupID.x].ppos[start + idx + BLOCK_SIZE];
    cachePvel[idx]              = edata[gl_WorkGroupID.x].pvel[start + idx];
    cachePvel[idx + BLOCK_SIZE] = edata[gl_WorkGroupID.x].pvel[start + idx + BLOCK_SIZE];
    #else
    cachePpos[idx]              = res[start + idx];
    cachePpos[idx + BLOCK_SIZE] = res[start + idx + BLOCK_SIZE];
    #endif
    barrier();

    for(uint delta = BLOCK_SIZE; delta > 0; delta >>= 1) {
        uint base = (idx & (delta-1)) | ((idx & ~(delta-1)) << 1);
        vec4 lhs     = cachePpos[base        ];
        vec4 rhs     = cachePpos[base + delta];
        #ifdef SORT_PPOS
        vec4 lhs_vel = cachePvel[base        ];
        vec4 rhs_vel = cachePvel[base + delta];
        #endif
        barrier();
        if((compare(lhs, rhs) ^ reverse) != 0) {
            cachePpos[base        ] = rhs;
            cachePpos[base + delta] = lhs;
            #ifdef SORT_PPOS
            cachePvel[base        ] = rhs_vel;
            cachePvel[base + delta] = lhs_vel;
            #endif
        } 
        barrier();
    }
    #ifdef SORT_PPOS
    edata[gl_WorkGroupID.x].ppos[start + idx]              = cachePpos[idx];
    edata[gl_WorkGroupID.x].ppos[start + idx + BLOCK_SIZE] = cachePpos[idx + BLOCK_SIZE];
    edata[gl_WorkGroupID.x].pvel[start + idx]              = cachePvel[idx];
    edata[gl_WorkGroupID.x].pvel[start + idx + BLOCK_SIZE] = cachePvel[idx + BLOCK_SIZE];
    #else
    res[start + idx]              = cachePpos[idx];
    res[start + idx + BLOCK_SIZE] = cachePpos[idx + BLOCK_SIZE];
    #endif
    barrier();
}

void presortCached(uint start, uint reverse) {
    const uint idx = gl_LocalInvocationID.x;
    #ifdef SORT_PPOS
    cachePpos[idx]              = edata[gl_WorkGroupID.x].ppos[start + idx];
    cachePpos[idx + BLOCK_SIZE] = edata[gl_WorkGroupID.x].ppos[start + idx + BLOCK_SIZE];
    cachePvel[idx]              = edata[gl_WorkGroupID.x].pvel[start + idx];
    cachePvel[idx + BLOCK_SIZE] = edata[gl_WorkGroupID.x].pvel[start + idx + BLOCK_SIZE];
    #else
    cachePpos[idx]              = res[start + idx];
    cachePpos[idx + BLOCK_SIZE] = res[start + idx + BLOCK_SIZE];
    #endif
    barrier();

    for(uint width = 1; width <= BLOCK_SIZE; width <<= 1) {
        uint local_reverse = (idx & width) != 0 ? 1 : 0;
        for(uint delta = width; delta > 0; delta >>= 1) {
            uint base = (idx & (delta-1)) | ((idx & ~(delta-1)) << 1);
            vec4 lhs     = cachePpos[base        ];
            vec4 rhs     = cachePpos[base + delta];
            #ifdef SORT_PPOS
            vec4 lhs_vel = cachePvel[base        ];
            vec4 rhs_vel = cachePvel[base + delta];
            #endif
            barrier();
            if((compare(lhs, rhs) ^ reverse ^ local_reverse) != 0) {
                cachePpos[base        ] = rhs;
                cachePpos[base + delta] = lhs;
                #ifdef SORT_PPOS
                cachePvel[base        ] = rhs_vel;
                cachePvel[base + delta] = lhs_vel;
                #endif
            } 
            barrier();
        }
    }
    #ifdef SORT_PPOS
    edata[gl_WorkGroupID.x].ppos[start + idx]              = cachePpos[idx];
    edata[gl_WorkGroupID.x].ppos[start + idx + BLOCK_SIZE] = cachePpos[idx + BLOCK_SIZE];
    edata[gl_WorkGroupID.x].pvel[start + idx]              = cachePvel[idx];
    edata[gl_WorkGroupID.x].pvel[start + idx + BLOCK_SIZE] = cachePvel[idx + BLOCK_SIZE];
    #else
    res[start + idx]              = cachePpos[idx];
    res[start + idx + BLOCK_SIZE] = cachePpos[idx + BLOCK_SIZE];
    #endif
    barrier();
}

void bitonicSort(uint start, uint size) {
    for(uint i = 0; i < size; i += 2 * BLOCK_SIZE) {
        presortCached(start+i, (i & (2 * BLOCK_SIZE)) != 0 ? 1 : 0);
    }
    barrier();
    for(uint width = 2 * BLOCK_SIZE; width < size; width <<= 1) {
        for(uint i = 0; i < size; i += 2 * width) {
            uint reverse = (i & (2*width)) != 0 ? 1 : 0;
            //Bitonic block start
            for(uint delta = width; delta > BLOCK_SIZE; delta >>= 1) {
            // for(uint delta = width; delta > 0; delta >>= 1) {
                for(uint block = 0; block < width; block += BLOCK_SIZE) {
                    uint idx = block + gl_LocalInvocationID.x;
                    uint base = (idx & (delta-1)) | ((idx & ~(delta-1)) << 1);
                    
                    #ifdef SORT_PPOS
                    vec4 lhs     = edata[gl_WorkGroupID.x].ppos[start + i + base        ];
                    vec4 rhs     = edata[gl_WorkGroupID.x].ppos[start + i + base + delta];
                    vec4 lhs_vel = edata[gl_WorkGroupID.x].pvel[start + i + base        ];
                    vec4 rhs_vel = edata[gl_WorkGroupID.x].pvel[start + i + base + delta];
                    #else
                    vec4 lhs = res[start + i + base        ];
                    vec4 rhs = res[start + i + base + delta];
                    #endif
                    barrier();
                    if((compare(lhs, rhs) ^ reverse) != 0) {
                        vec4 tmp = rhs;
                        rhs = lhs;
                        lhs = tmp;
                        #ifdef SORT_PPOS
                        tmp = rhs_vel;
                        rhs_vel = lhs_vel;
                        lhs_vel = tmp;
                        #endif
                    }
                    #ifdef SORT_PPOS
                    edata[gl_WorkGroupID.x].ppos[start + i + base        ] = lhs;
                    edata[gl_WorkGroupID.x].ppos[start + i + base + delta] = rhs;
                    edata[gl_WorkGroupID.x].pvel[start + i + base        ] = lhs_vel;
                    edata[gl_WorkGroupID.x].pvel[start + i + base + delta] = rhs_vel;
                    #else
                    res[start + i + base        ] = lhs;
                    res[start + i + base + delta] = rhs;
                    #endif
                    barrier();
                }
            }
            for(uint block = 0; block < 2 * width; block += 2 * BLOCK_SIZE) {
                sortCached(start + i + block, reverse);
            }

        }
    }
    barrier();
}


void sortParticles(uint emitterIndex, uint lastCount) {
#ifdef SORT_PPOS
    uint offset = 0;
    uint size = ceilPowerOfTwo(max(lastCount, 64u));
#else
    uint n = cmd[emitterIndex].instanceCount;
    uint offset = cmd[emitterIndex].firstInstance;
    uint size = ceilPowerOfTwo(max(n, 64u));
#endif

#ifdef SORT_PPOS
    bitonicSort(offset, size);
    moveToRes(emitterIndex);
#else
    moveToRes(emitterIndex);
    bitonicSort(offset, size);
#endif
}

uint typeVertexCount(uint type) {
    if(type == 4) return 14;
    if(type == 6) return 2 * einfo[gl_WorkGroupID.x].count;
    return 4;
}

uint emitterComparator(uint i) {
    vec4 lhs = einfo[i].position;
    vec4 rhs = einfo[gl_WorkGroupID.x].position;
    if(lhs == rhs) {
        return i < gl_WorkGroupID.x ? 1 : 0;
    }
    return (world.mProjView[0] * vec4(lhs.xyz, 1)).z > (world.mProjView[0] * vec4(rhs.xyz, 1)).z ? 1 : 0;
}

shared uint emitterIndex;
uint emitterStartPos() {
    reducerBuf[gl_LocalInvocationID.x] = 0;
    emitterIndex = 0;
    barrier();
    for(uint i = 0; i < N_MAX_EMITTERS; i += BLOCK_SIZE) {
        if (i + gl_LocalInvocationID.x < gl_NumWorkGroups.x && emitterComparator(i + gl_LocalInvocationID.x) != 0) {
            atomicAdd(emitterIndex, 1);
            reducerBuf[gl_LocalInvocationID.x] += ceilPowerOfTwo(max(2*BLOCK_SIZE, einfo[i+gl_LocalInvocationID.x].count)); //TODO: Take spawning into account
        }
    }
    barrier();
    bufReduce();
    uint start = reducerBuf[0];
    if(gl_LocalInvocationID.x == 0) {
        cmd[emitterIndex].vertexCount   = typeVertexCount(einfo[gl_WorkGroupID.x].type);
        cmd[emitterIndex].instanceCount = einfo[gl_WorkGroupID.x].count;
        cmd[emitterIndex].firstVertex   = 0;
        cmd[emitterIndex].firstInstance = start;
        einfo[gl_WorkGroupID.x].pad[0]  = emitterIndex;
        einfo[emitterIndex]    .pad[1]  = gl_WorkGroupID.x;
    }
    barrier();
    
    return emitterIndex;
}



void main() {
    randSeed = 0;
    const uint prevSize = min(N_MAX_PARTICLES_PER_EMITTER, einfo[gl_WorkGroupID.x].count+1);
    simulateEmitter(0, N_MAX_PARTICLES_PER_EMITTER);

    uint emitterIndex = emitterStartPos();

    sortParticles(emitterIndex, prevSize);
    
    if(gl_LocalInvocationID.x == 0) {
        if(params.frameTime - espawn[gl_WorkGroupID.x].lastSpawnTime > espawn[gl_WorkGroupID.x].rate && einfo[gl_WorkGroupID.x].count < N_MAX_PARTICLES_PER_EMITTER) {
            emitParticle(einfo[gl_WorkGroupID.x].count);
            espawn[gl_WorkGroupID.x].lastSpawnTime = params.frameTime;
        }
        if(einfo[gl_WorkGroupID.x].type == 6) {
            cmd[emitterIndex].instanceCount = 1;
        }
    }
}