#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_GOOGLE_include_directive : require

#include "particleInfo.hpp"
#include "projview.hpp"

struct DrawIndirectCommand {
    uint vertexCount;
    uint instanceCount;
    uint firstVertex;
    uint firstInstance;
};

#define BLOCK_SIZE PARTICLE_SIMULATOR_BLOCK_SIZE
layout(local_size_x = BLOCK_SIZE) in;

layout(set = 0, binding = 0, std430) buffer et_t{
  EmitterInfo einfo[N_MAX_EMITTERS];
};


layout(set = 0, binding = 1) buffer res_t  { vec4 res [N_MAX_PARTICLES_TOTAL]; };
layout(set = 0, binding = 2) buffer cmd_t  { DrawIndirectCommand cmd [N_MAX_EMITTERS]; };

layout(set = 0, binding = 3) buffer ppos_t { vec4 ppos[N_MAX_PARTICLES_PER_EMITTER]; vec4 pvel[N_MAX_PARTICLES_PER_EMITTER]; } edata[N_MAX_EMITTERS];

layout(set = 1, binding = 0) uniform WVPM_t {
  WorldViewProjMatrices world;
};


layout(push_constant) uniform pc {
    mat4 mProjView;
    float frameTime;
    float dt;
} params;

float rand(vec2 c){
	return fract(sin(dot(c.xy, vec2(12.7898,78.233)) + cos(dot(c.xy, vec2(-12315.5767, 3524.56)))) * 43718.5453);
}

shared uint randSeed;
float randf() {
    return rand(params.frameTime * vec2(gl_WorkGroupID.x, atomicAdd(randSeed, 1)));
}

vec3 randnvec3() {
    return normalize(2 * vec3(randf(), randf(), randf()) - vec3(1));
}

void emitParticle(uint dst) {
    // uint emitter = gl_WorkGroupID.x;
    // const vec3 pos = einfo[emitter].position.xyz + einfo[emitter].spawnRadius * randnvec3();
    // const vec3 dir = mix(randnvec3(), einfo[emitter].direction.xyz, einfo[emitter].directionFactor);

    // const vec3 vel = einfo[emitter].maxSpeed * mix(1, randf(), einfo[emitter].speedRandomFactor) * dir;

    // ppos[dst].xyz = pos;
    // ppos[dst].w = 1;
    // barrier();

    // pvel[dst].xyz = vel;
    // pvel[dst].w   = -1 / einfo[emitter].lifetime;
    // barrier();
}


shared uint reducerBuf[BLOCK_SIZE];
void bufReduce() {
    barrier();
    if(gl_LocalInvocationID.x + BLOCK_SIZE / 2 < BLOCK_SIZE) {
    #if BLOCK_SIZE >= 2
        reducerBuf[gl_LocalInvocationID.x] += reducerBuf[gl_LocalInvocationID.x + BLOCK_SIZE /    2];
    #endif
    #if BLOCK_SIZE >= 4
        reducerBuf[gl_LocalInvocationID.x] += reducerBuf[gl_LocalInvocationID.x + BLOCK_SIZE /    4];
    #endif
    #if BLOCK_SIZE >= 8
        reducerBuf[gl_LocalInvocationID.x] += reducerBuf[gl_LocalInvocationID.x + BLOCK_SIZE /    8];
    #endif
    #if BLOCK_SIZE >= 16
        reducerBuf[gl_LocalInvocationID.x] += reducerBuf[gl_LocalInvocationID.x + BLOCK_SIZE /   16];
    #endif
    #if BLOCK_SIZE >= 32
        reducerBuf[gl_LocalInvocationID.x] += reducerBuf[gl_LocalInvocationID.x + BLOCK_SIZE /   32];
    #endif
    #if BLOCK_SIZE >= 64
        reducerBuf[gl_LocalInvocationID.x] += reducerBuf[gl_LocalInvocationID.x + BLOCK_SIZE /   64];
    #endif
    #if BLOCK_SIZE >= 128
        reducerBuf[gl_LocalInvocationID.x] += reducerBuf[gl_LocalInvocationID.x + BLOCK_SIZE /  128];
    #endif
    #if BLOCK_SIZE >= 256
        reducerBuf[gl_LocalInvocationID.x] += reducerBuf[gl_LocalInvocationID.x + BLOCK_SIZE /  256];
    #endif
    #if BLOCK_SIZE >= 512
        reducerBuf[gl_LocalInvocationID.x] += reducerBuf[gl_LocalInvocationID.x + BLOCK_SIZE /  512];
    #endif
    #if BLOCK_SIZE >= 1024
        reducerBuf[gl_LocalInvocationID.x] += reducerBuf[gl_LocalInvocationID.x + BLOCK_SIZE / 1024];
    #endif
    #if BLOCK_SIZE >= 2048
    #error "BLOCK_SIZE >= 2048 not implemented"
    #endif
    }
    barrier();
}

shared uint spawnSemaphore;

void simulateEmitter(uint start, uint size) {
    // dead[gl_LocalInvocationID.x] = 0;
    // bool needSpawn = params.frameTime - einfo[gl_WorkGroupID.x].lastSpawnTime > einfo[gl_WorkGroupID.x].rate;
    // spawnSemaphore = 0;
    // barrier();
    // for(uint batch = 0; batch < (size + (BLOCK_SIZE - 1)) / BLOCK_SIZE; batch++) {
    //     uint idx = start + BLOCK_SIZE * batch + gl_LocalInvocationID.x;
    //     vec4 pos = ppos[idx] + pvel[idx] * 0.5 * params.dt;
    //     barrier();
    //     ppos[idx] = pos;
    //     if(pos.w <= 0) {
    //         dead[gl_LocalInvocationID.x] += 1;
    //         if(needSpawn && spawnSemaphore == 0 && atomicAdd(spawnSemaphore, 1) == 0) {
    //             emitParticle(idx);
    //             needSpawn = false;
    //             einfo[gl_WorkGroupID.x].lastSpawnTime = params.frameTime;
    //         }
    //     }
    //     barrier();
    //     // pos.w = pos.w < 0 ? 0.5 : 0;//min(1, 1-pos.w);
    //     pos.w = min(1, 1-pos.w);
    //     // pos.xyz = (world.mProjView[0] * vec4(pos.xyz, 1)).xyz;
    //     res[idx] = pos;
    //     barrier(); 
    // }
    // deadReduce();
    // barrier(); 
    // if(gl_LocalInvocationID.x == 0) {
    //     einfo[gl_WorkGroupID.x].count = size - dead[0];
    // }
    // barrier(); 
}

uint compare(vec4 lhs, vec4 rhs) {
    uint live1 = lhs.w < 1 ? 1 : 0;
    uint live2 = rhs.w < 1 ? 1 : 0;
    if(live1 != live2) 
        return live1 < live2 ? 1 : 0;
    return (world.mProjView[0] * vec4(lhs.xyz, 1)).z < (world.mProjView[0] * vec4(rhs.xyz, 1)).z ? 1 : 0;
}

shared vec4 cachePpos[2 * BLOCK_SIZE];
void sortCached(uint start, uint reverse) {
    const uint idx = gl_LocalInvocationID.x;
    cachePpos[idx]              = res[start + idx];
    cachePpos[idx + BLOCK_SIZE] = res[start + idx + BLOCK_SIZE];
    barrier();

    for(uint delta = BLOCK_SIZE; delta > 0; delta >>= 1) {
        uint base = (idx & (delta-1)) | ((idx & ~(delta-1)) << 1);

        vec4 lhs = cachePpos[base        ];
        vec4 rhs = cachePpos[base + delta];
        barrier();
        if((compare(lhs, rhs) ^ reverse) != 0) {
            cachePpos[base        ] = rhs;
            cachePpos[base + delta] = lhs;
        } 
        barrier();
    }
    res[start + idx]              = cachePpos[idx];
    res[start + idx + BLOCK_SIZE] = cachePpos[idx + BLOCK_SIZE];
    barrier();
}

void presortCached(uint start, uint reverse) {
    const uint idx = gl_LocalInvocationID.x;
    cachePpos[idx]              = res[start + idx];
    cachePpos[idx + BLOCK_SIZE] = res[start + idx + BLOCK_SIZE];
    barrier();

    for(uint width = 1; width <= BLOCK_SIZE; width <<= 1) {
        uint local_reverse = (idx & width) != 0 ? 1 : 0;
        for(uint delta = width; delta > 0; delta >>= 1) {
            uint base = (idx & (delta-1)) | ((idx & ~(delta-1)) << 1);
            vec4 lhs = cachePpos[base        ];
            vec4 rhs = cachePpos[base + delta];
            barrier();
            if((compare(lhs, rhs) ^ reverse ^ local_reverse) != 0) {
                cachePpos[base        ] = rhs;
                cachePpos[base + delta] = lhs;
            } 
            barrier();
        }
    }
    res[start + idx]              = cachePpos[idx];
    res[start + idx + BLOCK_SIZE] = cachePpos[idx + BLOCK_SIZE];
    barrier();
}

void bitonicSort(uint start, uint size) {
    for(uint i = 0; i < size; i += 2 * BLOCK_SIZE) {
        presortCached(start+i, (i & (2 * BLOCK_SIZE)) != 0 ? 1 : 0);
    }
    barrier();
    for(uint width = 2 * BLOCK_SIZE; width < size; width <<= 1) {
        for(uint i = 0; i < size; i += 2 * width) {
            uint reverse = (i & (2*width)) != 0 ? 1 : 0;
            //Bitonic block start
            // for(uint delta = width; delta > 2 * BLOCK_SIZE; delta >>= 1) {
            for(uint delta = width; delta > 0; delta >>= 1) {
                for(uint block = 0; block < width; block += BLOCK_SIZE) {
                    uint idx = block + gl_LocalInvocationID.x;
                    uint base = (idx & (delta-1)) | ((idx & ~(delta-1)) << 1);
                    vec4 lhs = res[start + i + base        ];
                    vec4 rhs = res[start + i + base + delta];
                    barrier();
                    if((compare(lhs, rhs) ^ reverse) != 0) {
                        vec4 tmp = rhs;
                        rhs = lhs;
                        lhs = tmp;
                    } 
                    res[start + i + base        ] = lhs;
                    res[start + i + base + delta] = rhs;
                    barrier();
                }
            }
            // sortCached(start + i, reverse);
        }
    }
    barrier();
}

uint ceilPowerOfTwo(uint v) {
    v--;
    v |= v >> 1;
    v |= v >> 2;
    v |= v >> 4;
    v |= v >> 8;
    v |= v >> 16;
    v++;
    return v;
}

void sortParticles(uint emitterIndex) {
    uint n = cmd[emitterIndex].instanceCount;
    uint size = ceilPowerOfTwo(max(n, 64u));
    uint offset = cmd[emitterIndex].firstInstance;
    for(uint i = 0; i < size; i += BLOCK_SIZE) {
        if(i + gl_LocalInvocationID.x >= n) {
            res[offset + i + gl_LocalInvocationID.x] = vec4(0, 0, 0, 2);
        }
        barrier();
    }
    bitonicSort(offset, size);
}

uint typeVertexCount(uint type) {
    if(type == 4) return 14;
    return 4;
}

uint emitterComparator(uint i) {
    vec4 lhs = einfo[i].position;
    vec4 rhs = einfo[gl_WorkGroupID.x].position;
    if(lhs == rhs) {
        return i < gl_WorkGroupID.x ? 1 : 0;
    }
    return (world.mProjView[0] * vec4(lhs.xyz, 1)).z > (world.mProjView[0] * vec4(rhs.xyz, 1)).z ? 1 : 0;
}

shared uint emitterIndex;
uint emitterStartPos() {
    reducerBuf[gl_LocalInvocationID.x] = 0;
    emitterIndex = 0;
    barrier();
    for(uint i = 0; i < N_MAX_EMITTERS; i += BLOCK_SIZE) {
        if (i + gl_LocalInvocationID.x < gl_NumWorkGroups.x && emitterComparator(i + gl_LocalInvocationID.x) != 0) {
            atomicAdd(emitterIndex, 1);
            reducerBuf[gl_LocalInvocationID.x] += ceilPowerOfTwo(max(2*BLOCK_SIZE, einfo[i+gl_LocalInvocationID.x].count)); //TODO: Take spawning into account
        }
    }
    barrier();
    bufReduce();
    uint start = reducerBuf[0];
    if(gl_LocalInvocationID.x == 0) {
        cmd[emitterIndex].vertexCount   = typeVertexCount(einfo[gl_WorkGroupID.x].type);
        cmd[emitterIndex].instanceCount = einfo[gl_WorkGroupID.x].count;
        cmd[emitterIndex].firstVertex   = 0;
        cmd[emitterIndex].firstInstance = start;
        einfo[gl_WorkGroupID.x].pad[0]  = emitterIndex;
        einfo[emitterIndex]    .pad[1]  = gl_WorkGroupID.x;
    }
    barrier();
    for(uint i = 0; i < N_MAX_PARTICLES_PER_EMITTER; i += BLOCK_SIZE) {
        res[start + i + gl_LocalInvocationID.x] = edata[gl_WorkGroupID.x].ppos[i + gl_LocalInvocationID.x];
    }
    barrier();
    return emitterIndex;
}

void main() {
    randSeed = 0;

    uint emitterIndex = emitterStartPos();

    // simulateEmitter(gl_WorkGroupID.x * 2 * BLOCK_SIZE, 2 * BLOCK_SIZE);
    // uint eid = gl_WorkGroupID.x;

    sortParticles(emitterIndex);
    
    // if(gl_LocalInvocationID.x == 0) {
    //     cmd[eid].vertexCount = typeVertexCount(einfo[eid].type);
    //     cmd[eid].instanceCount = 64;//einfo[eid].count;
    //     cmd[eid].firstVertex   = 0;
    //     cmd[eid].firstInstance = eid * 2 * BLOCK_SIZE;
    // }
}