name: linux

on: [push, pull_request]

permissions:
  contents: read

# mostly stolen from
# https://github.com/fmtlib/fmt
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cxx: [g++-12, clang++-18]
        build_type: [Debug, RelWithDebInfo, Release]
        include:
          - cxx: g++-12
            install: sudo apt install g++-12
          - cxx: clang++-18
            cxxflags: -stdlib=libc++
            install: sudo apt install clang-18 libc++-18-dev libc++abi-18-dev

    steps:
    - uses: actions/checkout@v4

    - name: Prepare Vulkan SDK
      uses: humbletim/install-vulkan-sdk@main
      with:
        version: 1.3.290.0
        cache: true

    - name: Install CMake
      run: | 
        sudo apt install cmake

    - name: Create Build Environment
      run: |
        sudo apt update
        ${{matrix.install}}
        sudo apt install libwayland-dev libxkbcommon-dev xorg-dev
        cmake -E make_directory ${{runner.workspace}}/build

    - name: Set up CPM cache
      id: cache-cpm
      uses: actions/cache@v4
      with:
        path: ~/cpm-cache
        key: ${{ runner.os }}-cpm-${{ hashFiles('**/') }}
        restore-keys: |
          ${{ runner.os }}-cpm-

    - name: Configure
      working-directory: ${{runner.workspace}}/build
      env:
        CXX: ${{matrix.cxx}}
        CXXFLAGS: ${{matrix.cxxflags}}
      run: |
        cmake -DCPM_SOURCE_CACHE=~/cpm-cache \
          -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
          $GITHUB_WORKSPACE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: |
        threads=`nproc`
        cmake --build . --config ${{matrix.build_type}} --parallel $threads
